name: Create Release

on:
  push:
    tags: ["v*.*.*"]

permissions:
  contents: write

jobs:
  build_release:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          npm run build -- --base-href /$REPO_NAME/

      - name: ZIP Assets
        run: |
          cd dist/$REPO_NAME/browser
          zip -r ../../../release-assets.zip .
          cd ../../../

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} release-assets.zip --generate-notes
